### ISSUE TITLE
Keycode is not drawn

### ISSUE THREAD

**Issue by Econa77** [Kentzo/ShortcutRecorder#40]
If register a shortcut in the demo app, keycode is not drawn.
Is this by design? Is this in the specifications?

For example register a shortcut "⌘ + Shift + v" at "Global Png".
In this Image, not drawn keyCode.

![2015-06-06 15 18 36](https://cloud.githubusercontent.com/assets/2995438/8018606/35c41a52-0c60-11e5-8667-279b93a54462.png)

**Comment by Kentzo** [comment]
Hi,

It's definitely not by design and not by specifications. If key code cannot be caught, nothing should be drawn.

I wasn't able to reproduce that with cmd + shift + v though: I activated the corresponding recorder, typed cmd + shift + v and it was recorded and drawn.

![screen shot 2015-06-06 at 10 44 18](https://cloud.githubusercontent.com/assets/88809/8020298/30ccad88-0c39-11e5-8f80-31cdf1b15411.png)

**Comment by Kentzo** [comment]
@Econa77 Were you able to fix that?

**Comment by jongampark** [comment]
I saw that no modifiers are drawn on OS X 10.10.3, while they were drawn on OS X 10.10.5.
I just grab the latest source code by clicking "Sync" on a GitHub desktop app, but doesn't look to have a fix for that.

**Comment by Kentzo** [comment]
@jongampark Thanks. Were you able to reliably reproduce it?

**Comment by jongampark** [comment]
It should be. However, the machine with OS X 10.10.3 is not my machine, but my manager's. I can't test on his machine, because he uses his machine all day long.
That's one of a problem to figure out exact reason why it doesn't display the modifier symbols.
However, even on my OS X 10.10.5, from time to time, if I click the widget to change hot key, it displays the widget with blank text. ( right after clicking it to edit ) Probably it's related. Probably that's good starting point to investigate it.

**Comment by jongampark** [comment]
Hmmm.. somehow on my 10.10.5 with the demo app, it always displays hot key modifiers and key now.
The check-in log shows that the latest one is 17 days ago, but I checked out code initially about 2 weeks ago. So, it should have contained all the latest code, but when I 'synched' today, it got some newer code.
Probably it's fixed? I am not sure, because changed code are mostly about changing "NSUInteger" to "NSEventModifierFlag"

**Comment by jongampark** [comment]
Ah... it happened on OS X 10.10.5 machine ( my machine )

**Comment by jongampark** [comment]
I took video with my other machine. ( If I tried so on the same machine or tried to take a screenshot, this problem doesn't happen. It looks to me that it's about 'redrawing' issue. )
https://youtu.be/kh9Qn1GVwvU

How I made it happen on this OS X 10.10.5 machine is by clicking those two shortcut controller widget in turns repeatedly. At some point, it happens. When it happens depends on your luck.
I wonder why this problem is quite visible and happens more on 10.10.3. Probably it's how Cocoa framework works on 10.10.3 vs. 10.10.5. Apple may flushes and initiates redrawing more frequently on 10.10.5.

**Comment by Kentzo** [comment]
Could you record a video via QutickTime?

**Comment by Kentzo** [comment]
You said you were able to reproduce it by clicking view repeatedly. How were you able to do that? After a click you can finish recording only by entering key combo, clicking ESC or one of the buttons.

**Comment by jongampark** [comment]
I did this repeatedly.

Click 2nd SRRecoderController widget.
Click 3rd SRRecoderController widget.
Click 2nd SRRecoderController widget.
Click 3rd SRRecoderController widget.
...

--
I wonder if the symptom happening on my machine is same to the one reported here originally and what I see on my manager's machine.
On this page, modifiers are shown while key code is not.
On my manager's machine, modifiers are NOT shown while key code IS.
On my 10.10.5, nothing appears.

Can be related... or can be independent issue.

**Comment by jongampark** [comment]
With the Demo app ( and with my small fix ), I tried on my manager's machine just a few secs ago.
And it looked to work. Let me integrated it to our app and see if it works there.
If things works, probably I check in my small modification.

**Comment by jongampark** [comment]
This became trickier. Although a problem in this framework became a little better now, I see a problem with our hosting app. If built in debug mode, everything works fine. If built in release mode, it doesn't display modifier keys. Our hosting app doesn't use ARC. I wonder why it works in debug build.

**Comment by jongampark** [comment]
On our side, optimization level for release mode ( Fastest/Smallest ) didn't like it. Only when I changed it to -O0, it showed modifiers/keys.
However, I know that the Demo app has the same fastest/smallest option for optimization. So, I wonder why our side of integration caused a problem. One thing clear is that this library uses ARC, while our hosting one doesn't. It can be related to that. Probably turning on optimizer strips off some valuable information thinking that those are not used.

**Comment by Kentzo** [comment]
@jongampark What are the specs of the machine you're working on?
How do you add view to your personal app?

**Comment by Kentzo** [comment]
What I suggest is to try to test it with Quartz Debug (Tools -> Flash Screen Updates). See if view gets redrawn.

**Comment by Kentzo** [comment]
Also, try to comment out the following lines:

https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L534-L535
https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L619-L620
https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L635-L636
https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L672-L673

**Comment by Kentzo** [comment]
Would make sense to log all calls in the draw* methods. Should be obvious is something is not called when you expect it to be called.

**Comment by Kentzo** [comment]
@jongampark Another think I'd suggest to try, is to change height from 25 to 24 in https://github.com/Kentzo/ShortcutRecorder/blob/master/Demo/IKCodeAutoLayoutWindowController.m#L87

I noticed, that overall height, despite that constraint, is calculated incorrectly: it's extended with alignmentRectInsets. I'm yet to find why it may affect drawing, but please check.

**Comment by jongampark** [comment]
@Kentzo  Thank you for your suggestion. However I tried different approach. Instead of commenting those lines out, I called needsDisplay. It reduced the problematic cases. However, it still happened.
I think, yes.. the code change you mentioned should be applied generally, because the problem happened whether it's Release or Debug build. It looks to me that temporal moment when OS X determines that it needs refresh is sort of different from Release/Debug and different version of OS X. 
Well, especially from OS X 10.10 ~ 10.11, I already noticed differences when redrawing took place.
It looks to me that it's due to Apple's change in auto layout and underling changes for Metal etc. ( Inheritently there NSVIew will depends on, or at least there should be code to use Metal or not, and such changes could affect this behavior. Actually I talked to a person at Apple for such case about a month ago. )

However, unfortunately, there was more than those described above.
I found out that optimization option -O0 ( no optimization; for debug build ) only worked. If it's anything above than that, it had the problem. Default optimization option for Release build is "Fastest and Smallest", which is -Os. It's strange. Probably it's related to the fact that our host app doesn't utilize ARC. Probably optimizer determined something wrongly and stripped off some symbols.
( I tried dead code stripping mode. Well, even though it's turned off, optimizer strips of code, which is determined to be not used. )

In addition to that, I added an option not to display the "revert" button.
I know that displaying such "return" symbol for exiting editing mode has existed from NeXTStep era and sometime until Xcode 4 era. ( even on System Preferences -> Keyboard shortcut )
However, people at work get confused about it. They tout themselves as Mac guys but they don't seem to know how it was before they used Mac OS X. Anyway, I didn't check in my changes yet.

If you want to have the functionality to hide "return" button, I'll.

**Comment by Kentzo** [comment]
@jongampark I tried my best, but I cannot reproduce this behavior at all.

Please confirm that drawing methods are called. Also, please try the `develop` branch, I fixed a minor issue, but don't understand how it may affect this bug.

**Comment by Kentzo** [comment]
@jongampark Ultimately, please write me at kulakov.ilya@gmail.com it would be awesome if I'd have direct access to the machine (TeamViewer, VNC, whatever) to debug it.

**Comment by jongampark** [comment]
I'm sorry but I may not allow others to access my computers at work. Let me try checking in my changes to develop branch when I go back home and let me try to replicate the problem at home.

One thing I worry is that my home machine is updated to OS X 10.11 while my Mac Pro at work is still is OS X 10.10.

**Comment by Kentzo** [comment]
@jongampark If you can set up VM where I can reproduce it, it will be great as well. I think the issue may require certain hardware to reproduce.

**Comment by jongampark** [comment]
@Kentzo I didn't have a chance to check in my small fix. However, our SQA people found that this problem still happens ( which is slightly different from the issue with optimization option. I mean the original issue reported here originally )
Anyway let me try to replicate the problem when I go back home ( hopefully ) today. I didn't have a chance yesterday.

Also, I don't think it's H/W issue. Nowadays even warm boot doesn't introduce much problem as the days of Apple II/ IBM XT/AT era. 
My Mac Pro is pretty general one, Late 2013, 3.7Ghz Quad-Core Intel Xeon E5, 12GB of memory, AMD FirePro D300 2GB graphics card and machines our SQA uses are also general.

**Comment by Kentzo** [comment]
@jongampark Can be easily related to a particular implementation of OpenGL drivers. And I do not have any other explanation of why I cannot reproduce this at all :)

**Comment by jongampark** [comment]
Our SQA machine : 
Mac Pro 4,1 (early 2009)
Dual Xeon 2.26 GHz Quad-Core
8GB 1066 MHz DDR3 ECC
Mac OS 10.10.5
ATI Radeon HD 5770 1024MB

My machine :
Mac Pro (Late 2013)
3.7 Ghz Quad-Core Intel Xeon E5
12GB 1866 MHz DDR3 ECC
AMD FirePro D300 2048MB

**Comment by jongampark** [comment]
I tried this : 

-----------------
@jongampark Another think I'd suggest to try, is to change height from 25 to 24 in https://github.com/Kentzo/ShortcutRecorder/blob/master/Demo/IKCodeAutoLayoutWindowController.m#L87

I noticed, that overall height, despite that constraint, is calculated incorrectly: it's extended with alignmentRectInsets. I'm yet to find why it may affect drawing, but please check.
-----------------

On my machine, it became harder to reproduce the problem. Probably it fixed the problem? I didn't reproduce it yet. So, I don't know.

**Comment by jongampark** [comment]
Ah... but..  IKCodeAutoLayoutWindowController.m is not part of the framework.
I wrapped your framework in our own framework, which is written on top of Cocoa and Carbon.
So, the trick will not solve the problem.

BTW, let me change other files ( which you said to comment out some lines in them ) to see if it becomes any better.

**Comment by jongampark** [comment]
In addition to commenting out those lines to by pass drawing elements, I added needsDisplay in drawInterior: message ( as well as drawLabel:, which I did so already )
Let's see if things get any better.

**Comment by jongampark** [comment]
Using Quartz Debug, I confirmed that the widget area is being updated, which I confirmed at the first place...

**Comment by Kentzo** [comment]
@jongampark As of size of the widget in the CodeAutoLayout demo: I think it's a bug in Cocoa which only happens when you add constraints by hand. Because it's calculated correctly (25) in the IBAutoLayout demo.

Another thing to try: override [-rectForLabel:withAttributes:](https://github.com/Kentzo/ShortcutRecorder/blob/develop/Library/SRRecorderControl.m#L297-L329) to return `self.bounds`. This will cause label to be drawn in the wrong place, but we will be able to check if issue is related to incorrectly calculated bounds.

**Comment by jongampark** [comment]
Oh.. Thank you for the information. If SQA reports back to me that they still have the problem, let me try the one you suggested.

**Comment by jongampark** [comment]
Finally SQA gave me some feedback. What I did was to comment out what the lines you said.
When I tested a few days ago ( before checking in to our SVN repo ), it worked fine and looked to me that the symptom is lessened a lot. However, now it became worse, and actually the behavior became very same to original description of this issue #40.

I tried to press Shift-<number>. Then it displays only the Shift symbol. Once it starts to malfunction, pressing option-control-<other keys> also doesn't work as expected.

https://www.youtube.com/watch?v=zkdFjogIbtM

**Comment by Kentzo** [comment]
@jongampark Have you tried to override `-rectForLabel:withAttributes:` to return bounds?

**Comment by jongampark** [comment]
No, not yet. I checked in code before you mentioned it. I'm working on other issues, but let me quickly test that.

**Comment by Kentzo** [comment]
@jongampark Sure, no rush :)

**Comment by jongampark** [comment]
![how it looks on our host app](https://cloud.githubusercontent.com/assets/138396/10492147/2c009bca-725f-11e5-9b95-3294b33586ab.png)
This is how it looks and behave on our app.
Don't worry about the height. I can adjust it. However, although it only shows top tip of the text, I can see that it still displays * for 8 when pressing Shift-8.

Anyway, what you asked to change is for determining the bounds where things to be drawn.
However, problems we see is not bound issue, but what characters to be drawn there.
I understand why you wanted to check the bound. In the original problem, the key code is not drawn. So, there can be a chance that the key code portion was somehow clipped due to somehow wrong bound for area for the text to be drawn. However, now it becomes clear that the problem is more than that.
For some keys, unexpected symbols are drawn ( like * for 8 when pressing Shift-8, & for pressing Shift-7, or sometimes it doesn't display the number part at all. )

There looks to be some edge case or peculiar case to address, which doesn't show its face when trying with a pure Cocoa app of which GUI is prepared with Interface Builder.

Can you look more thoroughly in that direction? This one requires conceptual debugging or debugging-in-our-brain-than-with-debugger. 

In the case of @Econa77, he looked to make it happen with the demo app or pure Cocoa app. So, if he provides some more detailed feedback, it can be more helpful.

**Comment by jongampark** [comment]
Just in case these two screenshots shows how it render text differently when returning self.bound and returning labelRect.

![return self bounds](https://cloud.githubusercontent.com/assets/138396/10492309/2d9b2ad0-7260-11e5-960f-1b3231ac32d5.png)
[Image 1] When returning self.bound

![original](https://cloud.githubusercontent.com/assets/138396/10492319/3c7523e4-7260-11e5-8ebf-0c298cb7aac7.png)
[Image 2] when returning labelRect.

**Comment by Kentzo** [comment]
@jongampark That's expected. But can you reproduce "truncation" when you return `self.bounds` from `rectForLabel:…` ?

**Comment by Kentzo** [comment]
@jongampark I really think that's a clipping issue. Either due to height or due to width constraints. It's the only thing that can break it. Take a look at the `drawLabel` code: it's simple and uses Cocoa's API.

**Comment by Kentzo** [comment]
It's completely unclear why you see * to be drawn instead of 8 "sometimes": it will either happen always or not happen at all. Could you create a separate issue for that?

**Comment by jongampark** [comment]
Ok. Actually I took a look at the drawLabel code a while ago. Let me double-check that code.

Yes. I also wonder why it displays * instead of 8 'sometimes'. I didn't see it before, but today I keep seeing it. Let me create an issue.

**Comment by jongampark** [comment]
I figured out why the problem happened.

Although it happens very rarely, the key code part becomes 0xFFFF sometimes. Why I saw the problem more often with my app was that it fires events by its own event manager, which is wrapped around Cocoa's. I found out that it fired some intermediate state of key press. 
With the demo app, the possibility that it happens is much lower, but it does happen.

Anyway, when it happened, [SRRecorderControl objectValue] didn't convey 4 key/value pairs. For example, it should be like this:
{
    characters = 7;
    charactersIgnoringModifiers = "&";
    keyCode = 26;
    modifierFlags = 1179648;
}

Probably my fix would not quite visible if used with pure Cocoa app, because it happens rarely. But let me try to check in.

**Comment by Kentzo** [comment]
@jongampark Is it on Mac OS X or on other platforms you run?

**Comment by jongampark** [comment]
@kentzo it is Mac OS X only of course! It cannot run on Windows!

**Comment by Kentzo** [comment]
Oh, from the comment to #48 I thought you ported it on other platforms.

**Comment by Kentzo** [comment]
0xFFFF (or 65535) is usually sent along with key modifiers. In what method did you receive key code of 65535 exactly?

**Comment by jongampark** [comment]
In most cases, we have our own middle-tier framework on top of Carbon/Cocoa. We pump events in its own scheduling policy. There it looked to me that it pumped some intermediate events.

Second case is with the Demo app. We know that it rarely happens there right? However when I clicked the control multiple times quickly. It sometimes happened. At that moment,key code was not drawn. I noticed that if it's 0xFFFF, it fails in drawing ( or giving up ) internally ( by Cocoa itself.. I guess. )

**Comment by Kentzo** [comment]
I'll need to simulate this. This can happen if the `keyDown` or `performKeyEquivalent` was called with keyCode of 65535 which shouldn't really ever happen, since such event is key-less.

If you have some time, could you add NSLog to both of the methods above and log keyCode to see, if you will be able to send event of key 65535 there.

**Comment by Kentzo** [comment]
Code was merged into master. Hopefully it won't be seen again.

**Comment by fenfeilove** [comment]
there has some problem 
![7a25c9f1-e10c-4dc3-8374-85d0b892f3f4](https://cloud.githubusercontent.com/assets/12816473/26821689/d84caed8-4ad9-11e7-87a0-f9e306c1c61e.png)

**Comment by Kentzo** [comment]
@fenfeilove what is the key code? What key did you press on the keyboard?
